steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/nifty-inkwell-462806-n1/deoker/app:$SHORT_SHA',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/nifty-inkwell-462806-n1/deoker/app:$SHORT_SHA'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'my-cloud-run-service',
      '--image=us-central1-docker.pkg.dev/nifty-inkwell-462806-n1/deoker/app:$SHORT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'services', 'add-iam-policy-binding', 'my-cloud-run-service',
      '--region=us-central1',
      '--member=allUsers',
      '--role=roles/run.invoker'
    ]
    
images:
  - 'us-central1-docker.pkg.dev/nifty-inkwell-462806-n1/deoker/app:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

